apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tou-db

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: crunchy-monitoring
    vendor: crunchydata

resources:
- grafana
- prometheus
- alertmanager
