apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tou-db

secretGenerator:
- name: pgo-gcs-creds
  files:
  - gcs.conf
  - gcs-key.json

generatorOptions:
  disableNameSuffixHash: true
  
resources:
- ha-postgres.yaml
